// Lesson6/Offline/login-then-showlist/pages/login/index.tsx
import { useState } from 'react';
import { firebaseClient } from '../../auth/firebaseClient';

export default function Page() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    return <div>
        <div className="background"></div>
        <div className="fade-in container d-flex vh-100 vw-100">
            <div className="authform authform--transpgray authform--shadow mx-auto my-auto">
                <form className="form-group">
                    <h3 className="authform__title text-center my-3">Login</h3>
                    <input value={email}
                           type={"email"}
                           onChange={(e) => setEmail(e.target.value)}
                           placeholder={'Email'}
                           className="form-control authform--text-input d-block w-75 mt-1 mx-auto p-2"/>
                    <input type={'password'}
                           value={password}
                           onChange={(e) => setPassword(e.target.value)}
                           placeholder={'Password'}
                           className="form-control authform--text-input d-block w-75 mt-1 mx-auto p-2"/>
                    <button
                        type={"button"}
                        className="btn btn-primary text-truncate d-block w-75 p-1 mt-3 mb-1 mx-auto"
                        onClick={async () => {
                            await firebaseClient.auth().signInWithEmailAndPassword(email, password)
                                .then(() => window.location.href = '/list')
                                .catch(error => alert(error.message));
                        }}>
                        Log in
                    </button>
                </form>
            </div>
        </div>
    </div>
}

// Lesson5/Offline/showlist-app/src/app/modules/auth/pages/login/login.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthenticationService } from '@core/services/authentication.service';

@Component({
  selector: 'app-login',
  templateUrl: 'login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit, OnDestroy {
  email: string;
  password: string;
  isLoading = false;
  constructor(public authenticationService: AuthenticationService, public router: Router) {
    this.email = '';
    this.password = '';
    this.isLoading = false;
    console.log("LoginComponent is loaded");
  }
  ngOnInit(): void {
    this.isLoading = false;
  }
  ngOnDestroy(): void {
    this.email = '';
    this.password = '';
    this.isLoading = false;
  }
  login(): void {
    if (this.isLoading) {
      return;
    }
    this.isLoading = true;
    this.authenticationService.login(this.email, this.password)
      .then((value) => {
        console.log('succesful login with value = ', value);
        this.isLoading = false;
        this.router.navigate(['/home']);
      })
      .catch((err) => {
        console.log('failed login with message = ', err.message);
        this.isLoading = false;
        alert(err.message);
      });
  }
}

<div class="background"></div>
<div class="fade-in container d-flex vh-100 vw-100">
  <div class="authform authform--transpgray authform--shadow mx-auto my-auto" *ngIf="loginForm">
    <form class="form-group" [formGroup]="loginForm" (ngSubmit)="login()">
      <h3 class="authform__title text-center my-3">Login</h3>

      <input class="form-control authform--text-input d-block w-75 mt-1 mx-auto p-2"
             type="text"
             placeholder="Enter email"
             formControlName= "email"
             [ngClass]="{ 'is-invalid': this.email?.touched && this.email?.errors }"
             autofocus/>
      <div *ngIf="email?.touched && email?.errors" class="invalid-feedback text-center w-75 h-100 mx-auto">
        <div *ngIf="email?.errors?.required" class="small">Email is required</div>
        <div *ngIf="email?.errors?.email" class="small">Email must be valid</div>
        <div *ngIf="email?.errors?.maxlength" class="small">Email is too long</div>
      </div>
      <input class="form-control authform--text-input d-block w-75 mt-1 mx-auto p-2"
             type="password"
             placeholder="Enter password"
             formControlName= "password"
             [ngClass]="{ 'is-invalid': this.password?.touched && this.password?.errors }"/>
      <div *ngIf="password?.touched && password?.errors" class="text-center invalid-feedback w-75 h-100 mx-auto">
        <div *ngIf="password?.errors?.required" class="small">Password is required</div>
        <div *ngIf="password?.errors?.minlength" class="small">Password is too short</div>
        <div *ngIf="password?.errors?.maxlength" class="small">Password is too long</div>
      </div>
      <p class="text-center small font-weight-normal mt-1 w-75 mx-auto">
        <span>Not a member? </span>
        <a class="font-weight-weight" [routerLink]="'/auth/register'" (mousedown)="false">
          <strong>Sign up</strong>
        </a>
      </p>
      <button type="submit"
              class="btn btn-primary text-truncate d-block w-75 p-1 mt-3 mb-1 mx-auto"
              [disabled]="loginForm.invalid || isLoading">
        Login
      </button>
    </form>
  </div>
</div>
