// Lesson6/Offline/login-then-showlist/pages/login/index.tsx
import { useState } from 'react';
import { firebaseClient } from '../../auth/firebaseClient';

export default function Page() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    return <div>
        <div className="background"></div>
        <div className="fade-in container d-flex vh-100 vw-100">
            <div className="authform authform--transpgray authform--shadow mx-auto my-auto">
                <form className="form-group">
                    <h3 className="authform__title text-center my-3">Login</h3>
                    <input value={email}
                           type={"email"}
                           onChange={(e) => setEmail(e.target.value)}
                           placeholder={'Email'}
                           className="form-control authform--text-input d-block w-75 mt-1 mx-auto p-2"/>
                    <input type={'password'}
                           value={password}
                           onChange={(e) => setPassword(e.target.value)}
                           placeholder={'Password'}
                           className="form-control authform--text-input d-block w-75 mt-1 mx-auto p-2"/>
                    <button
                        type={"button"}
                        className="btn btn-primary text-truncate d-block w-75 p-1 mt-3 mb-1 mx-auto"
                        onClick={async () => {
                            await firebaseClient.auth().signInWithEmailAndPassword(email, password)
                                .then(() => window.location.href = '/list')
                                .catch(error => alert(error.message));
                        }}>
                        Log in
                    </button>
                </form>
            </div>
        </div>
    </div>
}

// Lesson3/Offline/AuthAndRouting/src/app/components/auth/login/login.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {AuthenticationService} from "../../../_services/authentication.service";
import {Router} from "@angular/router";

@Component({
  selector: 'app-login',
  templateUrl: 'login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit, OnDestroy {
  email: string;
  password: string;
  isLoading = false;
  constructor(public authenticationService: AuthenticationService, public router: Router) {
    this.email = '';
    this.password = '';
    this.isLoading = false;
  }
  ngOnInit(): void {
    this.isLoading = false;
  }
  ngOnDestroy(): void {
    this.email = '';
    this.password = '';
    this.isLoading = false;
  }
  login(): void {
    if (this.isLoading) {
      return;
    }
    this.isLoading = true;
    this.authenticationService.login(this.email, this.password)
      .then((value) => {
        console.log("succesful login with value = ", value);
        this.isLoading = false;
        this.router.navigate(['/main']);
      })
      .catch((err) => {
        console.log("failed login with message = ", err.message);
        this.isLoading = false;
        alert(err.message);
      });
  }
}

<div class="background"></div>
<div class="fade-in container d-flex vh-100 vw-100">
  <div class=" credentials-form credentials-form__gray w-75 text-center mx-auto my-auto">
    <h2 class="my-3">Login</h2>
    <input class="credentials-text-input d-block w-75 my-1 mx-auto p-2" type="text" [(ngModel)]="email" placeholder="Enter email"/>
    <input class="credentials-text-input d-block w-75 mt-1 mb-5 mx-auto p-2" type="password" [(ngModel)]="password" placeholder="Enter password"/>

    <button class="btn btn-primary text-truncate w-75 d-block p-1 my-1 mx-auto" (click)="login()" [disabled]="!email || !password || isLoading">
      Login
    </button>
    <button class="btn btn-secondary text-truncate w-75 d-block p-1 mt-1 mb-3 mx-auto" [routerLink]="'/auth/register'">
      I don't have an account
    </button>
  </div>
</div>
